version: "3.0"

services:
  redis-master:
    container_name: redis-master
    image: redis:alpine3.13
    ports:
      - "6379:6379"
      - "26379:26379"
    volumes:
      - ./myredis/conf:/usr/local/etc/redis
    #      - ./myredis/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf && redis-sentinel /usr/local/etc/redis/sentinel.conf"

  redis-slave:
    container_name: redis-slave
    image: redis:alpine3.13
    ports:
      - "6380:6380"
      - "26380:26380"
    volumes:
      - ./myredis/conf:/usr/local/etc/redis
    #      - ./myredis/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    command:
      [ "sh","-c","redis-server /usr/local/etc/redis/redis-slave.conf && redis-sentinel /usr/local/etc/redis/sentinel1.conf" ]

  redis-slave1:
    container_name: redis-slave1
    image: redis:alpine3.13
    ports:
      - "6381:6381"
      - "26381:26381"
    volumes:
      - ./myredis/conf:/usr/local/etc/redis
    #      - ./myredis/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - redis
    command:
      [ "sh","-c","redis-server /usr/local/etc/redis/redis-slave1.conf && redis-sentinel /usr/local/etc/redis/sentinel2.conf" ]

#volumes:
#  data:

networks:
  redis: